import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name:  "REFURBISHED DELL E5470",
      slug: "refurbished-dell-e5470",
      category: "Dell",
      image: "/img/dell5470.jpg",
       
      featuredImage: "/images/banner1.jpg",
      price: 25500.0,
      core: "I5",
      ram: "8GB",
      disk: "500GB",
      modal: "E5470",
      generation:"5th Generation",
    display:"14 inch",
      brand: "Dell",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "REFURBISHED DELL E5470",
      relateImages: 
  [ "/img/dell5470.jpg","/img/dell6430.jpg","/img/dell5470.jpg","/img/dell7240.jpg"]
     
      ,
    },
    {
      name: "REFURBISHED DELL E5450",
      slug: "refurbished-dell0e5450",
      category: "Dell",
      image: "/img/dell5470-2.jpeg",
      isFeatured: true,
      featuredImage:  "/img/dell.jpg",
      price:23500.00,
      core: "I5",
      ram: "8GB",
      disk: "500GB",
      modal: "E5450",
      generation:"5th Generation",
    display:"14 inch",
      brand: "Dell",
      
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED DELL E5450",
      relateImages: 
      [ "/img/dell5470-2.jpeg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name: "REFURBISHED HP 840 G3",
      slug: "refurbished-hp-840-g3",
      category: "HP",
      image: "/img/hp840g3.jpg",
      price: 26000.00,
      brand: "HP",
      core: "I5",
      ram: "8GB",
      disk: "500GB",
      modal: "840 G3",
      generation:"5th Generation",
    display:"14 inch",
      isFeatured: true,
      featuredImage:  "/img/hp.jpg",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED HP 840 G3",
       relateImages: 
       [ "/img/hp840g3.jpg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name:  "REFURBISHED  LENOVO T450",
      slug: "refurbished-lenovo-T450",
      category: "Lenovo",
      image: "/img/lenovoT440-2.jpg",
      price: 23000.00,
    brand: "Lenovo",
    core: "I5",
    ram: "8GB",
    disk: "500GB",
    modal: "T450",
    generation:"5th Generation",
    display:"14 inch",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking REFURBISHED  LENOVO T450", relateImages: 
      [ "/img/lenovoT440-2.jpg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name:"REFURBISHED LENOVO T440",
      slug: "refurbished-lenovo-T440",
      category: "Lenovo",
      image: "/img/lenovoT440-1.jpeg",
      price: 21500.00,
    brand: "Lenovo",
    core: "I5",
    ram: "8GB",
    disk: "500GB",
    modal: "T440",
    generation:"5th Generation",
    display:"14 inch",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED LENOVO T440", relateImages: 
      [ "/img/lenovoT440-1.jpeg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name: "REFURBISHED Dell E6430 Laptop",
      slug: "refurbished-dell-E6430",
      category: "Dell",
      image: "/img/dell6430.jpg",
      price: 20000.00,
    brand: "Dell",
    core: "I5",
    ram: "8GB",
    disk: "500GB",
    modal: "E6430",
    generation:"5th Generation",
    display:"14 inch",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED Dell E6430 Laptop", relateImages: 
      [ "/img/dell6430.jpg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name: "REFURBISHED LENOVO T460",
      slug: "refurbished-lenovo-T460",
      category: "Lenovo",
      image: "/img/lenovoT460.jpeg",
      price: 26000.00,
    brand: "Lenovo",
    core: "I5",
    ram: "8GB",
    disk: "500GB",
    modal: "T460",
    generation:"5th Generation",
    display:"14 inch",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED LENOVO T460", relateImages: 
      [ "/img/lenovoT460.jpeg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
    {
      name:"REFURBISHED HP 820 G3",
      slug: "refurbished-hp-820-G3",
      category: "HP",
      image: "/img/hp840G2.jpg",
      price: 23500.00,
    brand: "HP",
    core: "I5",
    ram: "8GB",
    disk: "500GB",
    modal: "820 G3",
    generation:"5th Generation",
    display:"14 inch",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular REFURBISHED HP 820 G3", relateImages: 
      [ "/img/hp840G2.jpg","/img/dell5470.jpg","/img/dell6430.jpg","/img/dell7240.jpg"]
    },
  ],
};
export default data;
