import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'REFURBISHED DELL E5470',
      slug: 'refurbished-dell-e5470',
      category: 'Dell',
      image: '/dellImg/dell5470-1.jpg',

      featuredImage: '/img/plain-white-background.jpg',
      price: 26000.0,
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: 'E5470',
      generation: '6th Generation',
      display: '14 inch',
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'REFURBISHED DELL E5470',
      relateImages: [
        '/dellImg/dell5470-2.jpg',
        '/dellImg/dell5470-3.jpg',
        '/dellImg/dell5470-4.jpg',
        '/dellImg/dell5470-5.jpg',
      ],
    },
    {
      name: 'REFURBISHED DELL E5450',
      slug: 'refurbished-dell0e5450',
      category: 'Dell',
      image: '/dellImg/dell5450-1.jpg',
      isFeatured: true,
      featuredImage: '/img/plain-white-background.jpg',
      price: 23500.0,
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E5450',
      generation: '5th Generation',
      display: '14 inch',
      brand: 'Dell',

      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED DELL E5450',
      relateImages: [
        '/dellImg/dell5450-1.jpg',
        '/dellImg/dell5450-2.jpg',
        '/dellImg/dell5450-3.jpg',
        '/dellImg/dell5450-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 840G3',
      slug: 'refurbished-hp-840-g3',
      category: 'HP',
      image: '/hpImg/hp840g3-2.jpg',
      price: 26000.0,
      brand: 'HP',
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: '840 G3',
      generation: '6th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp840g3-1.jpg',
        '/hpImg/hp840g3-2.jpg',
        '/hpImg/hp840g3-3.jpg',
        '/hpImg/hp840g3-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 820 G3',
      slug: 'refurbished-hp-820-g3',
      category: 'HP',
      image: '/hpImg/hp820g3-1.jpg',
      price: 22000.0,
      brand: 'HP',
      core: 'I5',
      ram: '8GB',
      disk: '500GB HDD',
      modal: '820 G3',
      generation: '6th Generation',
      display: '12.5 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp820g3-1.jpg',
        '/hpImg/hp820g3-2.jpg',
        '/hpImg/hp820g3-3.jpg',
        '/hpImg/hp820g3-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 820 G4',
      slug: 'refurbished-hp-820-g4',
      category: 'HP',
      image: '/hpImg/hp820g4-1.jpg',
      price: 28000.0,
      brand: 'HP',
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: '820 G4',
      generation: '7th Generation',
      display: '12.5 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp820g4-1.jpg',
        '/hpImg/hp820g4-2.jpg',
        '/hpImg/hp820g4-3.jpg',
        '/hpImg/hp820g4-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 440 G2',
      slug: 'refurbished-hp-440-g2',
      category: 'HP',
      image: '/hpImg/hp440g2-1.jpg',
      price: 22000.0,
      brand: 'HP',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: '440 G2',
      generation: '4th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp440g2-1.jpg',
        '/hpImg/hp440g2-2.jpg',
        '/hpImg/hp440g2-3.jpg',
        '/hpImg/hp440g2-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 430 G2',
      slug: 'refurbished-hp-430-g2',
      category: 'HP',
      image: '/hpImg/hp430g2-1.jpg',
      price: 20500.0,
      brand: 'HP',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: '430 G2',
      generation: '4th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp430g2-1.jpg',
        '/hpImg/hp430g2-2.jpg',
        '/hpImg/hp430g2-3.jpg',
        '/hpImg/hp430g2-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 430 G4',
      slug: 'refurbished-hp-430-g4',
      category: 'HP',
      image: '/hpImg/hp430g2-1.jpg',
      price: 30500.0,
      brand: 'HP',
      core: 'I7',
      ram: '8GB',
      disk: '256GB SSD',
      modal: '430 G2',
      generation: '7th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp430g2-1.jpg',
        '/hpImg/hp430g2-2.jpg',
        '/hpImg/hp430g2-3.jpg',
        '/hpImg/hp430g2-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 840 G1',
      slug: 'refurbished-hp-840-g1',
      category: 'HP',
      image: '/hpImg/hp840g1-1.jpg',
      price: 22500.0,
      brand: 'HP',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: '840 G1',
      generation: '4th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp840g1-1.jpg',
        '/hpImg/hp840g1-2.jpg',
        '/hpImg/hp840g1-3.jpg',
        '/hpImg/hp840g1-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 840 G2',
      slug: 'refurbished-hp-840-g2',
      category: 'HP',
      image: '/hpImg/hp840g2-1.jpg',
      price: 23000.0,
      brand: 'HP',
      core: 'I5',
      ram: '8GB',
      disk: '500GB HDD',
      modal: '840 G2',
      generation: '5th Generation',
      display: '14 inch',
      isFeatured: true,
      featuredImage: '/img/banneer2.jpg',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 840 G3',
      relateImages: [
        '/hpImg/hp840g2-1.jpg',
        '/hpImg/hp840g2-2.jpg',
        '/hpImg/hp840g2-3.jpg',
        '/hpImg/hp840g2-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED HP 840 G3',
      slug: 'refurbished-hp-840-G3',
      category: 'HP',
      image: '/hpImg/hp840g3-2.jpg',
      price: 29500.0,
      brand: 'HP',
      core: 'I7',
      ram: '8GB',
      disk: '256GB SSD',
      modal: '840 G3',
      generation: '6th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED HP 820 G3',
      relateImages: [
        '/hpImg/hp840g3-1.jpg',
        '/hpImg/hp840g3-2.jpg',
        '/hpImg/hp840g3-3.jpg',
        '/hpImg/hp840g3-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED  LENOVO T420',
      slug: 'refurbished-lenovo-T420',
      category: 'Lenovo',
      image: '/lenovoImg/lenovoT420-1.jpg',
      price: 16000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'T420',
      generation: '2th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking REFURBISHED  LENOVO T450',
      relateImages: [
        '/lenovoImg/lenovoT420-1.jpg',
        '/lenovoImg/lenovoT420-2.jpg',
        '/lenovoImg/lenovoT420-5.jpg',
        '/lenovoImg/lenovoT420-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T430',
      slug: 'refurbished-lenovo-T430',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT430-1.jpg',
      price: 17000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'T430',
      generation: '3th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT430-1.jpg',
        '/lenovoImg/lenovoT430-2.jpg',
        '/lenovoImg/lenovoT430-5.jpg',
        '/lenovoImg/lenovoT430-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T440',
      slug: 'refurbished-lenovo-T440',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT440-1.jpg',
      price: 21000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'T440',
      generation: '4th Generation',
      display: '14 inch',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT440-1.jpg',
        '/lenovoImg/lenovoT440-2.jpg',
        '/lenovoImg/lenovoT440-3.jpg',
        '/lenovoImg/lenovoT440-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T450',
      slug: 'refurbished-lenovo-T450',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT450-1.jpg',
      price: 22500.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'T450',
      generation: '5th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT450-1.jpg',
        '/lenovoImg/lenovoT450-2.jpg',
        '/lenovoImg/lenovoT450-3.jpeg',
        '/lenovoImg/lenovoT450-2.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T460',
      slug: 'refurbished-lenovo-T460',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT460-1.jpg',
      price: 26000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: 'T460',
      generation: '6th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT460-1.jpg',
        '/lenovoImg/lenovoT460-2.jpeg',
        '/lenovoImg/lenovoT460-3.jpg',
        '/lenovoImg/lenovoT460-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T470',
      slug: 'refurbished-lenovo-T470',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT470-1.jpg',
      price: 26500.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: 'T470',
      generation: '6th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT470-1.jpg',
        '/lenovoImg/lenovoT470-2.jpg',
        '/lenovoImg/lenovoT470-3.jpg',
        '/lenovoImg/lenovoT470-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO T440s',
      slug: 'refurbished-lenovo-T440s',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoT440s-1.jpg',
      price: 21500.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'T440s',
      generation: '4th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoT440s-1.jpg',
        '/lenovoImg/lenovoT440s-2.jpg',
        '/lenovoImg/lenovoT440s-3.jpg',
        '/lenovoImg/lenovoT440s-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO L440',
      slug: 'refurbished-lenovo-L440',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoL440-1.jpg',
      price: 20500.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'L440',
      generation: '4th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoL440-1.jpg',
        '/lenovoImg/lenovoL440-2.jpg',
        '/lenovoImg/lenovoL440-3.jpg',
        '/lenovoImg/lenovoL440-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO L430',
      slug: 'refurbished-lenovo-L430',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoL430-1.jpg',
      price: 16000.0,
      brand: 'Lenovo',
      core: 'I3',
      ram: '4GB',
      disk: '320GB HDD',
      modal: 'L430',
      generation: '3rd Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoL430-1.jpg',
        '/lenovoImg/lenovoL430-2.jpg',
        '/lenovoImg/lenovoL430-3.jpg',
        '/lenovoImg/lenovoL430-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO X240',
      slug: 'refurbished-lenovo-X240',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoX240-1.jpg',
      price: 21000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'X240',
      generation: '4th Generation',
      display: '12.5 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoX240-1.jpg',
        '/lenovoImg/lenovoX240-2.jpg',
        '/lenovoImg/lenovoX240-3.jpg',
        '/lenovoImg/lenovoX240-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO X250',
      slug: 'refurbished-lenovo-X250',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoX250-2.jpg',
      price: 23000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'X250',
      generation: '5th Generation',
      display: '12.5 inch',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoX250-1.jpg',
        '/lenovoImg/lenovoX250-2.jpg',
        '/lenovoImg/lenovoX250-3.jpg',
        '/lenovoImg/lenovoX250-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED LENOVO X260',
      slug: 'refurbished-lenovo-X260',
      category: 'Lenovo',
      image:  '/lenovoImg/lenovoX260-2.jpg',
      price: 25000.0,
      brand: 'Lenovo',
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: 'X260',
      generation: '6th Generation',
      display: '12.5 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED LENOVO T440',
      relateImages: [
        '/lenovoImg/lenovoX260-1.jpg',
        '/lenovoImg/lenovoX260-2.jpg',
        '/lenovoImg/lenovoX260-5.jpg',
        '/lenovoImg/lenovoX260-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED Dell E6420',
      slug: 'refurbished-dell-E6420',
      category: 'Dell',
      image: '/dellImg/dell6420-1.jpg',
      price: 16500.0,
      brand: 'Dell',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E6420',
      generation: '2nd Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED Dell E6430 Laptop',
      relateImages: [
        '/dellImg/dell6420-1.jpg',
        '/dellImg/dell6420-2.jpg',
        '/dellImg/dell6420-3.jpg',
        '/dellImg/dell6420-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED Dell E6430',
      slug: 'refurbished-dell-E6430',
      category: 'Dell',
      image: '/dellImg/dell6430-1.jpg',
      price: 18000.0,
      brand: 'Dell',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E6430',
      generation: '3rd Generation',
      display: '14 inch',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED Dell E6430 Laptop',
      relateImages: [
        '/dellImg/dell6430-1.jpg',
        '/dellImg/dell6430-2.jpg',
        '/dellImg/dell6430-3.jpg',
        '/dellImg/dell6430-4.jpeg',
      ],
    },
    {
      name: 'REFURBISHED Dell E6440',
      slug: 'refurbished-dell-E6440',
      category: 'Dell',
      image: '/dellImg/dell6440-1.jpg',
      price: 21000.0,
      brand: 'Dell',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E6440',
      generation: '4th Generation',
      display: '14 inch',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED Dell E6430 Laptop',
      relateImages: [
        '/dellImg/dell6440-1.jpg',
        '/dellImg/dell6440-2.jpg',
        '/dellImg/dell6440-3.jpg',
        '/dellImg/dell6440-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED Dell E3350',
      slug: 'refurbished-dell-E3350',
      category: 'Dell',
      image: '/dellImg/dell3350-1.jpg',
      price: 19000.0,
      brand: 'Dell',
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E3350',
      generation: '5th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED Dell E6430 Laptop',
      relateImages: [
        '/dellImg/dell3350-1.jpg',
        '/dellImg/dell3350-2.jpg',
        '/dellImg/dell3350-3.jpg',
        '/dellImg/dell3350-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED Dell E3340',
      slug: 'refurbished-dell-E3340',
      category: 'Dell',
      image: '/dellImg/dell3340-1.jpg',
      price: 17000.0,
      brand: 'Dell',
      core: 'I3',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E3340',
      generation: '4th Generation',
      display: '14 inch',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED Dell E6430 Laptop',
      relateImages: [
        '/dellImg/dell3340-1.jpg',
        '/dellImg/dell3340-2.jpeg',
        '/dellImg/dell3340-3.jpg',
        '/dellImg/dell3340-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED DELL E5430',
      slug: 'refurbished-dell-E5430',
      category: 'Dell',
      image: '/dellImg/dell5430-1.jpg',
      isFeatured: true,
      featuredImage: '/img/plain-white-background.jpg',
      price: 17000.0,
      core: 'I5',
      ram: '8GB',
      disk: '256GB SSD',
      modal: 'E5430',
      generation: '3rd Generation',
      display: '14 inch',
      brand: 'Dell',

      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED DELL E5450',
      relateImages: [
        '/dellImg/dell5430-1.jpg',
        '/dellImg/dell5430-2.jpg',
        '/dellImg/dell5430-3.jpg',
        '/dellImg/dell5430-4.jpg',
      ],
    },
    {
      name: 'REFURBISHED DELL E7440',
      slug: 'refurbished-dell-E7440',
      category: 'Dell',
      image: '/dellImg/dell7440-1.jpg',
      isFeatured: true,
      featuredImage: '/img/plain-white-background.jpg',
      price: 20000.0,
      core: 'I5',
      ram: '4GB',
      disk: '500GB HDD',
      modal: 'E7440',
      generation: '4th Generation',
      display: '12.5 inch',
      brand: 'Dell',

      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular REFURBISHED DELL E5450',
      relateImages: [
        '/dellImg/dell7440-1.jpg',
        '/dellImg/dell7440-2.jpg',
        '/dellImg/dell7440-3.jpeg',
        '/dellImg/dell7440-4.jpg',
      ],
    },
    
  
  ],
};
export default data;
